<?php

/**
 * SocietoPageBundle
 * Copyright (C) 2011 Kousuke Ebihara
 *
 * This program is under the EPL/GPL/LGPL triple license.
 * Please see the Resources/meta/LICENSE file that was distributed with this file.
 */

namespace Societo\PageBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PageGadgetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageGadgetRepository extends EntityRepository
{
    public function getByPage($page)
    {
        $results = array();

        $builder = $this->_em->createQueryBuilder();
        $builder->add('select', 'pg')
            ->add('from', 'Societo\PageBundle\Entity\PageGadget pg')
            ->add('where', 'pg.page = :page')
            ->add('orderBy', 'pg.sortOrder ASC, pg.createdAt DESC')
            ->setParameter('page', $page->getId());
        $q = $builder->getQuery();


        $gadgets = $q->getResult();

        foreach ($gadgets as $gadget) {
            $results[$gadget->getPoint()][] = $gadget;
        }

        return $results;
    }
}
